# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9589866d738c7f25b4ecb02494a789509993d62563b518356c0bbb34d427ed5f388a9864fa28ae6a5a8c1346cd5705a4d0b522cee2c29bfe8502353e2ebdcad

test:
  secret_key_base: 107435774b36a1bb74442c770ca9bb9f4c0b64ed2d761454ab0b95c3e4ab8aedb8af1fce7c195d97a223d96b7df658d9b08092ecfe77dd48668775c024089ef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
